name: test
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

env:
  JULIA_LANGSERVER: 3.2.0
jobs:
  test:
    name: test
    runs-on: macos-latest
    steps:
      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.6'
      
      - run: julia --version
      
      - run: julia --compile=min -O0 -e "using InteractiveUtils; versioninfo()"
        
      - run: which julia
      
      - run: echo "$PATH"
      
      - run: echo "/Users/runner/hostedtoolcache/julia/1.6.5/x64/bin" >> $GITHUB_PATH
      
      - run: echo "$PATH"
      
      - run: cat ~/.bash_profile
